/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.steganografia;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Konrad
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    
    
     BufferedImage image;
     int char_count;
     int bits_in_pixel;
    
    
    public Gui() {
        initComponents();
        input_text_field.setLineWrap(true);
        image_label.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bits_field = new javax.swing.JTextField();
        image_label = new javax.swing.JLabel();
        pixel_count_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_text_field = new javax.swing.JTextArea();
        save_button = new javax.swing.JButton();
        read_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output_text_field = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        read_input_button = new javax.swing.JButton();
        save_output_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        start_radio = new javax.swing.JRadioButton();
        end_radio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        horizontally_radio = new javax.swing.JRadioButton();
        vertical_radio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Wczytaj Obraz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ilosc bitów z kazdego pixela: ");

        bits_field.setText("3");
        bits_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bits_fieldActionPerformed(evt);
            }
        });

        image_label.setText("Wczytano obraz !");

        pixel_count_field.setEditable(false);

        jLabel3.setText("Wiadomosc która ma zostać osadzona: ");

        input_text_field.setColumns(20);
        input_text_field.setRows(5);
        jScrollPane1.setViewportView(input_text_field);

        save_button.setText("Zapisz Obraz");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        read_button.setText("Odczytaj Wiadomosc");
        read_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_buttonActionPerformed(evt);
            }
        });

        output_text_field.setColumns(20);
        output_text_field.setRows(5);
        jScrollPane2.setViewportView(output_text_field);

        jLabel5.setText("Wiadomosc odczytana:");

        read_input_button.setText("Wczytaj:");
        read_input_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_input_buttonActionPerformed(evt);
            }
        });

        save_output_button.setText("Zapisz");
        save_output_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_output_buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Zapisywanie wiadomosci od:");

        buttonGroup1.add(start_radio);
        start_radio.setText("Poczatku");

        buttonGroup1.add(end_radio);
        end_radio.setText("Konca");

        jLabel6.setText("Kierunek:");

        buttonGroup2.add(horizontally_radio);
        horizontally_radio.setText("Poziomo");

        buttonGroup2.add(vertical_radio);
        vertical_radio.setText("Pionowo");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setText("Algorytm najmniej znaczącego bitu");

        jLabel7.setText("Autor: Konrad Kurcaba");

        jButton2.setText("Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Min 1, Max 6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(save_button)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(read_input_button)
                                            .addGap(22, 22, 22))))
                                .addComponent(jLabel7))
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(94, 94, 94)
                                    .addComponent(read_button))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(save_output_button)
                                    .addGap(138, 138, 138))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(pixel_count_field, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(399, 399, 399)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(image_label))
                                .addComponent(jButton1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(362, 362, 362)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bits_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addGap(181, 181, 181)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(start_radio)
                                .addGap(64, 64, 64)
                                .addComponent(end_radio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(horizontally_radio)
                                .addGap(70, 70, 70)
                                .addComponent(vertical_radio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6)))
                        .addGap(95, 95, 95)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bits_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image_label)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pixel_count_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(end_radio)
                            .addComponent(start_radio)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horizontally_radio)
                            .addComponent(vertical_radio))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(read_input_button)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read_button)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_output_button)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Pliki BMP","BMP");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(null);
        File image_path;
       
       
        if(returnVal == fc.APPROVE_OPTION)
        {
            image_path = fc.getSelectedFile();
            try{
            
            image = ImageIO.read(image_path);
            int height = image.getHeight();
            int width = image.getWidth();
            int pixels = height * width;
            bits_in_pixel = Integer.parseInt(bits_field.getText());
            char_count= (pixels*bits_in_pixel )/ 16;
            char_count -= 2; // na znaki kontrolne
            pixel_count_field.setText("W tym obrazku mozesz osadzic "+char_count+" znakow");
            
            image_label.setVisible(true);
            input_text_field.setText("");
            output_text_field.setText("");
            }catch(Exception e)
            {
                
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bits_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bits_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bits_fieldActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        bits_in_pixel = Integer.parseInt(bits_field.getText());
        String text_field = input_text_field.getText();
        text_field = text_field.replace("\r", "");
        boolean start = true; // jesli od poczatku do konca to zmienna na true, jesli od konca do poczatku to na false
        if (end_radio.isSelected()) start = false;
        boolean direction = true;
        if (vertical_radio.isSelected()) direction = false; // jesli poziomo to zmienna na true, jesli pionowo to na false
        image_save worker = new image_save(image,bits_in_pixel,char_count,input_text_field.getText(),start,direction);
        worker.execute();
        
    }//GEN-LAST:event_save_buttonActionPerformed

    private void read_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_buttonActionPerformed
        // TODO add your handling code here:
        bits_in_pixel = Integer.parseInt(bits_field.getText());
        boolean start = true; // jesli od poczatku do konca to zmienna na true, jesli od konca do poczatku to na false
        if (end_radio.isSelected()) start = false;
        boolean direction = true;
        if (vertical_radio.isSelected()) direction = false; // jesli poziomo to zmienna na true, jesli pionowo to na false
        image_read worker = new image_read(image,bits_in_pixel,output_text_field,start,direction);
        worker.execute();
    }//GEN-LAST:event_read_buttonActionPerformed

    private void save_output_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_output_buttonActionPerformed
         
        
        JFileChooser fileChooser = new JFileChooser("");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Pliki tekstowe","txt");
        fileChooser.setFileFilter(filter);
        if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try
        {
        PrintWriter writer = new PrintWriter(file);
        writer.print(output_text_field.getText());
        writer.close();
        }catch(Exception e)
        {
            
            
        }
        }
    }//GEN-LAST:event_save_output_buttonActionPerformed

    private void read_input_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_input_buttonActionPerformed
        final JFileChooser fc = new JFileChooser("");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Pliki tekstowe","txt");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(null);
        if(returnVal == fc.APPROVE_OPTION)
        {
            
            try
            {
            
            FileInputStream fis = new FileInputStream(fc.getSelectedFile());
            byte[] data = new byte[(int) fc.getCurrentDirectory().length()];
            fis.read(data);
            fis.close();

            String str = new String(data, "UTF-8");
            str = str.replace("\0", "");
            input_text_field.setText(str);
            output_text_field.setText("");
            }catch(Exception e)
            {
                System.out.print(e.getMessage());
            }
           
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_read_input_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        message m = new message("Zaimplementowany przeze mnie algorytm to algorytm najmniej znaczącego bitu - algorytm ten służy do ukrywania informacji w obrazach\n" +
"Posiada możliwośc wybrania na ile bitów z każdego pixela ma być przeznaczone na przechowanie informacji.\n" +
"Algorytm najpierw osadza informacje w bitach koloru czerwonego, nastepnie w bitach koloru zielonego i niebieskiego\n" +
"Bity \"0101010101010101\" to bity kontrolne, osadzone wiadomosci od nich się zaczynaja, i na nich się kończą\n" +
"\n" +
"Dane wejsciowe - Obraz o dowolnej wielkosci w formacie BMP, tekst który ma być osadzony - o jego maksymalnej wielkosci\n" +
"użytkownik zostanie poinformowany, moze byc wczytany z pliku lub klawiatury.\n" +
"\n" +
"Rozmiar danych zależy od wiekosci obrazka\n" +
"\n" +
"Sposób osadzania wiadomości - można wybrać czy wiadomość ma być umieszczona od początku, czy końca pliku oraz czy kolejne bity\n" +
"maja być zapisywane w pionie czy w poziomie\n" +
"\n" +
"Algorytm zostal napisany w JAVIE - w IDE NetBeans");
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bits_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private java.awt.Canvas canvas1;
    private javax.swing.JRadioButton end_radio;
    private javax.swing.JRadioButton horizontally_radio;
    private javax.swing.JLabel image_label;
    private javax.swing.JTextArea input_text_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output_text_field;
    private javax.swing.JTextField pixel_count_field;
    private javax.swing.JButton read_button;
    private javax.swing.JButton read_input_button;
    private javax.swing.JButton save_button;
    private javax.swing.JButton save_output_button;
    private javax.swing.JRadioButton start_radio;
    private javax.swing.JRadioButton vertical_radio;
    // End of variables declaration//GEN-END:variables
}
